export 'package:flutter/material.dart';
export 'package:flutter/services.dart';
export 'package:flutter/widgets.dart';
export 'dart:convert';
export 'dart:io';
export 'package:google_fonts/google_fonts.dart';
export 'package:shared_preferences/shared_preferences.dart';
export '../main.dart';
export 'dart:async';
export 'package:dropdown_button2/dropdown_button2.dart';
export 'package:image_picker/image_picker.dart';
export 'package:google_maps_flutter/google_maps_flutter.dart';
export 'package:intl/date_symbol_data_local.dart'; // โหลดข้อมูล locale สำหรับการแสดงวันที่
export 'package:permission_handler/permission_handler.dart';
export 'package:file_picker/file_picker.dart';
export 'package:path_provider/path_provider.dart';
export 'package:font_awesome_flutter/font_awesome_flutter.dart';
export 'package:flutter_svg/flutter_svg.dart';
export 'package:device_info_plus/device_info_plus.dart';
export 'package:loading_animation_widget/loading_animation_widget.dart';
export 'package:awesome_bottom_bar/awesome_bottom_bar.dart';
export 'package:awesome_bottom_bar/widgets/inspired/inspired.dart';
export 'package:url_launcher/url_launcher.dart';
export 'package:video_player/video_player.dart';
export 'package:flutter_advanced_switch/flutter_advanced_switch.dart';
export 'package:signature/signature.dart';
export 'package:syncfusion_flutter_calendar/calendar.dart';
export 'package:percent_indicator/percent_indicator.dart';
export 'package:flutter_switch/flutter_switch.dart';
export 'package:multi_select_flutter/multi_select_flutter.dart';
export 'package:open_file/open_file.dart';
export 'package:xml/xml.dart'; // สำหรับอ่าน XML
export 'package:flutter_speed_dial/flutter_speed_dial.dart';
// export 'package:carousel_slider_plus/carousel_slider_plus.dart';
export 'package:flutter_custom_clippers/flutter_custom_clippers.dart';
export 'package:origamilift/import/origami_view/language/translate.dart';
export 'package:origamilift/import/origami_view/origami.dart';
export 'package:quickalert/quickalert.dart';
export 'package:carousel_slider/carousel_slider.dart';
// export 'package:smooth_page_indicator/smooth_page_indicator.dart';
export 'package:video_player_android/video_player_android.dart';